"use client";

import { useEffect } from "react";

const heroIconNames=new Set(["Omega Rugal","Terry Bogard","Mai Shiranui","Ada","Ryuichi","Edwin","Koschevoi","Mireya","Marcus","Whisper","Drake","Veronica","Tyronn","Xuanming","Sawyer","Tormund","Mia Scarlet Pyros","Phoenix","Alph","Zoltan","Lunarl","Lofili","Vivian","Lee","Samir","Gerd","Durga","Harton","Pasino","Aiksen","Gimes","Caesar","Flameborne","Devilian","Iwado","Inata","Lanchester","Vesaryon","Ekko","Flora","Platos"]);
const heroIconSlug=(name:string)=>name.toLowerCase().replace(/scarlet pyros/g,"scarlet-pyros").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function addHeroIcon(slot:HTMLElement){if(slot.querySelector(".formation-hero-icon"))return;const el=slot.querySelector("b"),name=el?.textContent?.trim();if(!name||!heroIconNames.has(name)||!el)return;const img=document.createElement("img");img.className="formation-hero-icon";img.src=`/icons/${heroIconSlug(name)}.png`;img.alt=`${name} portrait`;img.width=48;img.height=60;el.before(img)}
function readHeroStars(name:string){const s=document.querySelector<HTMLSelectElement>(`select[aria-label="${CSS.escape(name)} star level"]`),v=Number(s?.value??1);return Number.isFinite(v)?Math.min(5,Math.max(1,v)):1}
function addFormationReason(card:HTMLElement){if(card.querySelector(".formation-why"))return;const slots=card.querySelectorAll<HTMLElement>(".slot");if(slots.length<3)return;const left=slots[0],name=left.querySelector("b")?.textContent?.trim(),skill=left.querySelector("small")?.textContent?.trim(),lv=left.querySelector("span")?.textContent?.match(/Lv\s*(\d+)/i)?.[1];if(!name)return;const isMain=/MAIN/i.test(card.querySelector(".formation-head b")?.textContent??"");const why=document.createElement("div");why.className="formation-why";why.style.cssText="margin-top:10px;padding:9px 11px;border-radius:8px;background:rgba(255,255,255,.045);font-size:12px;line-height:1.45";why.innerHTML=isMain?`<b style="display:block;margin-bottom:3px">WHY THIS MAIN RALLY</b><span>Uses your full Main Rally march capacity. Preferred meta is the strongest owned Tyronn/Phoenix/Xuanming Shieldbearer with Ryuichi and Ada when available; legal owned fallbacks are used when needed.</span>`:`<b style="display:block;margin-bottom:3px">WHY THIS JOINER</b><span>LEFT priority: ${name} • ${skill||"active first War skill"} • War Skill Lv${lv??"?"} • ${"★".repeat(readHeroStars(name))}. This joiner uses 100,000 troops; supporting slots preserve stronger LEFT-skill heroes for other marches.</span>`;card.querySelector(".slots")?.after(why)}

let enhanceQueued=false;
function enhanceGenerator(){document.querySelectorAll<HTMLElement>(".formation-card .slot").forEach(addHeroIcon);document.querySelectorAll<HTMLElement>(".formation-card").forEach(addFormationReason);document.querySelectorAll<HTMLElement>(".result > .slots > .slot").forEach(addHeroIcon);}
function queueEnhance(){if(enhanceQueued)return;enhanceQueued=true;requestAnimationFrame(()=>{enhanceQueued=false;enhanceGenerator()})}
export default function FormationIconEnhancer(){useEffect(()=>{enhanceGenerator();const observer=new MutationObserver(mutations=>{if(mutations.some(m=>Array.from(m.addedNodes).some(n=>n.nodeType===Node.ELEMENT_NODE)))queueEnhance()});observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[]);return null}
